{{- if and (eq .Values.provider "gke") (.Values.ingress.enabled) }}
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: kubevious-certificate
  labels:
    app.kubernetes.io/component: {{ include "kubevious.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
spec:
  domains:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
{{- end }}