apiVersion: v2
name: kubevious
description: A Helm chart for Kubevious
type: application
keywords:
  - kubernetes ui
  - kubernetes web ui
  - kubernetes configuration checker
  - kubernetes validator
icon: https://kubevious.io/img/logo.png
version: 0.8.13
appVersion: 0.8.13
